lang: node_js
cache:
  directoris:
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build 
deploy
  provider: pages 
  edge: true,
  skip-cleanup: true,
  keep-history: true,
  github-token: $GitHUb_token
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy Release"
  on:
    branch: main


